[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kaden-mk/juan"
authors = ["kaden-mk"]
readme = "README.md"
rust-version = "1.97"

[workspace.dependencies]
la-arena = "0.3.1"
phf = { version = "0.14.0", features = ["macros"] }
thiserror = "2.0.20"
num-traits = "0.2.19"

juan-lang = { version = "0.0.0", path = "crates/juan" }
juan-lexer = { version = "0.1.0", path = "crates/juan-lexer" }
juan-parser = { version = "0.1.0", path = "crates/juan-parser" }
juan-span = { version = "0.1.0", path = "crates/juan-span" }
juan-ast = { version = "0.1.0", path = "crates/juan-ast" }
juan-bytecode = { version = "0.1.0", path = "crates/juan-bytecode" }
juan-compiler = { version = "0.1.0", path = "crates/juan-compiler" }
juan-vm = { version = "0.1.0", path = "crates/juan-vm" }
